package top

var descriptionMatch = map[string]string{

	// freedesktop projects
	"iio-sensor-proxy":   "https://github.com/hadess/iio-sensor-proxy",
	"switcheroo-control": "https://github.com/hadess/switcheroo-control",
	"networkmanager":     "https://github.com/freedesktop/networkmanager",
	"modemmanager":       "https://github.com/freedesktop/modemmanager",
	"dbus":               "https://github.com/freedesktop/dbus",
	"upowerd":            "https://github.com/freedesktop/upower",
	"polkitd":            "https://github.com/freedesktop/polkit",
	"accounts-daemon":    "https://github.com/freedesktop/accountsservice",
	"geoclue":            "https://github.com/freedesktop/geoclue",
	"colord":             "https://github.com/freedesktop/colord",

	// gnome components
	"gnome-shell":        "https://gnome.org",
	"nautilus":           "https://github.com/gnome/nautilus",
	"file-roller":        "https://github.com/gnome/file-roller",
	"gvfs":               "https://github.com/gnome/gvfs",
	"gsd":                "https://github.com/gnome/gnome-settings-daemon",
	"goa":                "https://github.com/gnome/gnome-online-accounts",
	"gjs":                "https://github.com/gnome/gjs",
	"gdm":                "https://github.com/gnome/gdm",
	"at-spi":             "https://github.com/gnome/at-spi2-core",
	"evolution":          "https://github.com/gnome/evolution",
	"dconf-service":      "https://github.com/gnome/dconf",
	"tracker-miner-fs-3": "https://github.com/gnome/tracker-miners",

	// system components source
	"system76-power": "https://github.com/pop-os/system76-power",
	"pop-upgrade":    "https://github.com/pop-os/upgrade",
	"hidpi-daemon":   "https://github.com/pop-os/hidpi-daemon",
	"touchegg":       "https://github.com/joseexposito/touchegg",
	"thermald":       "https://github.com/intel/thermal_daemon",
	"packagekitd":    "https://github.com/packagekit",
	"ibus":           "https://github.com/ibus",
	"acpid":          "https://github.com/distrotech/acpid",
	"xdg":            "https://github.com/flatpak/xdg-desktop-portal",
	"irqbalance":     "https://github.com/irqbalance",
	"fsnotifier":     "https://github.com/jetbrains/intellij-community/tree/master/native/fsnotifier",
	"auditd":         "https://github.com/linux-audit",
	"avahi-daemon":   "https://github.com/lathiat/avahi",
	"rtkit-daemon":   "https://github.com/heftig/rtkit",
	"wpa_supplicant": "https://github.com/digsrc/wpa_supplicant",
	"udisksd":        "https://github.com/storaged-project/udisks",
	"cups":           "https://github.com/openprinting/cups-filters",
	"fusermount":     "https://github.com/libfuse",
	"compiz":         "https://github.com/compiz-reloaded/compiz",

	// system components website
	"systemd":                 "https://systemd.io",
	"xorg":                    "https://x.org",
	"nacl_helper":             "https://nacl.cr.yp.to",
	"pulseaudio":              "http://pulseaudio.org",
	"io.elementary.appcenter": "https://appcenter.elementary.io",
	"fcitx":                   "https://fcitx-im.org",
	"fwupd":                   "https://fwupd.org",
	"bluetoothd":              "http://www.bluez.org",
	"rsyslogd":                "https://www.rsyslog.com",
	"pipewire":                "https://pipewire.org",

	// applications
	"virtualboxvm": "https://virtualbox.org",
	"chrome":       "https://google.com/chrome",
	"code":         "https://code.visualstudio.com",
	"lantern":      "https://lantern.io",
	"dbeaver":      "https://dbeaver.io",
	"insomnia":     "https://insomnia.rest",
	"blender":      "https://blender.org",
	"kazam":        "https://launchpad.net/kazam",
	"vlc":          "https://videolan.org",
	"goland.sh":    "https://jetbrains.com/go",
	"idea.sh":      "https://jetbrains.com/idea",

	// server components
	"sshd":         "https://openssh.com",
	"java":         "https://openjdk.java.net",
	"node":         "https://nodejs.org",
	"pm2":          "https://pm2.io",
	"dockerd":      "https://docker.com",
	"containerd":   "https://containerd.io",
	"mongod":       "https://mongodb.com",
	"redis-server": "https://redis.io",
	"minio":        "https://min.io",
	"nginx-svr":    "https://nginx.org",

	// tools
	"snapd":            "https://snapcraft.io",
	"pigz":             "https://zlib.net/pigz",
	"ffmpeg":           "https://ffmpeg.org",
	"go":               "https://go.dev",
	"/usr/bin/python3": "https://python.org",
	"python3":          "https://python.org",
	"python":           "https://python.org",
}
